<!-- Add XML Data -->
<!DOCTYPE library[<!ELEMENT library (books,members,staffs,publisher)>
<!ELEMENT books (book1,book2)>
	<!ELEMENT book1 (title,author,year,isbn,price)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT isbn (#PCDATA)>
		<!ELEMENT price (#PCDATA)>
	<!ELEMENT book2 (title,author,year,isbn,price)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT isbn (#PCDATA)>
		<!ELEMENT price (#PCDATA)>
<!ELEMENT members (member1,member2)>
	<!ELEMENT member1 (name,address,phone)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
	<!ELEMENT member2 (name,address,phone)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
<!ELEMENT staffs (staff1,staff2)>
	<!ELEMENT staff1 (name,address,phone)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
	<!ELEMENT staff2 (name,address,phone)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
<!ELEMENT publisher (name,address,phone)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT address (#PCDATA)>
	<!ELEMENT phone (#PCDATA)>
<!ATTLIST book1 bookid CDATA #REQUIRED>
<!ATTLIST book2 bookid CDATA #REQUIRED>
<!ATTLIST member1 memberid CDATA #REQUIRED>
<!ATTLIST member2 memberid CDATA #REQUIRED>
<!ATTLIST staff1 staffid CDATA #REQUIRED>
<!ATTLIST staff2 staffid CDATA #REQUIRED>
<!ATTLIST publisher publishid CDATA #REQUIRED>
]>

<library>
	<books>
	<book1 bookid="1">
		<title>AI</title>
		<author>vijay</author>
		<year>2003</year>
		<isbn>200566</isbn>
		<price>300</price>
	</book1>
	<book2 bookid="2">
		<title>wdt</title>
		<author>somu</author>
		<year>2004></year>
		<isbn>21566</isbn>
		<price>600</price>
	</book2>
	</books>
	<members>
	<member1 memberid="101">
		<name>tej</name>
		<address>kadapa</address>
		<phone>123456</phone>
	</member1>
	<member2 memberid="102">
		<name>deep</name>
		<address>kadapa</address>
		<phone>121324</phone>
	</member2>
	</members>
	<staffs>
	<staff1 staffid="201">
		<name>sasi</name>
		<address>kadapa</address>
		<phone>2132143</phone>
	</staff1>
	<staff2 staffid="202">
		<name>malli</name>
		<address>kadapa</address>
		<phone>234278921</phone>
	</staff2>
  </staffs>
	<publisher publishid="301">
		<name>neeraj</name>
		<address>srit</address>
		<phone>17912786</phone>
	</publisher>
</library>
 
